services:
  - type: web
    name: bytemind-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET
      - key: GROQ_API_KEY
      - key: FRONTEND_URL
  - type: static
    name: bytemind-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
